[package]
name = "tb"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
hashmap_macro = "0.1.0"
owo-colors = "4.2.1"
pest = "2.8.0"
pest_derive = "2.8.0"
strum = "0.27.1"
strum_macros = "0.27.1"
thiserror = "2.0.12"
